name = "lorenzozanna-edge"
main = "src/index.mjs"
compatibility_date = "2026-07-04"
workers_dev = false

[vars]
ROOT_DOMAIN = "lorenzozanna.com"

[[d1_databases]]
binding = "DB"
database_name = "lorenzozanna_content"
database_id = "909a730d-0eb9-458a-ae34-c97a597cdcc4"

[[routes]]
pattern = "api.lorenzozanna.com"
custom_domain = true

[[routes]]
pattern = "ph.lorenzozanna.com/"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/index.html"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/index.php"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/robots.txt"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/sitemap.xml"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/portfolio"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/portfolio.html"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/about"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/about.html"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/contact"
zone_name = "lorenzozanna.com"

[[routes]]
pattern = "ph.lorenzozanna.com/contact.html"
zone_name = "lorenzozanna.com"
